#!/bin/bash
#
#This is a scenefile generated by hueBerry

echo "Set Lights 11 = Guest Lightstrip"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":false,"bri":1,"sat":116,"xy":[0.4422, 0.4058],"transitiontime":100,"hue":8632}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/11/state
echo "Set Lights 10 = Mika Light"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":false,"bri":1,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/10/state
echo "Set Lights 13 = Dining Room"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":121,"xy":[0.4448, 0.4066],"transitiontime":100,"hue":15335}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/13/state
echo "Set Lights 12 = Brian Light"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/12/state
echo "Set Lights 14 = Hallway Lamp"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/14/state
echo "Set Lights 1 = Living Table"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":133,"xy":[0.4524, 0.4087],"transitiontime":100,"hue":15119}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/1/state
echo "Set Lights 3 = Living Sofa"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/3/state
echo "Set Lights 2 = Living Record"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":133,"xy":[0.4524, 0.4087],"transitiontime":100,"hue":15119}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/2/state
echo "Set Lights 5 = Living Bookcase"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":133,"xy":[0.4524, 0.4087],"transitiontime":100,"hue":15119}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/5/state
echo "Set Lights 4 = Living Downlight"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":133,"xy":[0.4524, 0.4087],"transitiontime":100,"hue":15119}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/4/state
echo "Set Lights 7 = Guest Lamp"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":false,"bri":1,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/7/state
echo "Set Lights 6 = Door Front"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":229,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/6/state
echo "Set Lights 9 = Door Kitchen"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/9/state
echo "Set Lights 8 = Bathroom Light"
curl --silent -H "Accept: application/json" -X PUT --data '{"on":true,"bri":254,"sat":-1,"xy":-1,"transitiontime":100,"hue":-1}' http://192.168.1.144/api/ZIu-JHuUh7IPa0EFXXBw7yAbAUd4IAGMiPHflp5X/lights/8/state
